---
title: "Software"
output: html_document
---

## R packages

```{r eval=FALSE}
install.packages("psych")
install.packages("dplyr")
install.packages("magrittr")
install.packages("tidyr")
install.packages("stringr")
install.packages("knitr")
install.packages("printr")
install.packages("DT")
install.packages("latex2exp")
install.packages("lubridate")
install.packages("readxl")
install.packages("sqldf")
install.packages("testthat")
install.packages("devtools")
install.packages("ggplot2")
install.packages("ggvis")
install.packages("Amelia") # for plotting missing data using 'missmap' function
install.packages("MASS") # for 'stepAIC' function
```

## R packages (science)

```{r eval=FALSE}
install.packages("rafalib")
install.packages("pheatmap")
install.packages("rsnps")
install.packages("qqman")
install.packages("coloc")
install.packages("corrplot")
```

## R packages (devtools)

```{r eval=FALSE}
library(devtools)
install_github("hadley/bigvis")
install_github("baptiste/gridextra")
```

## Bioconductor packages

```{r eval=FALSE}
source("http://bioconductor.org/biocLite.R") # or install_bioc() from rafalib
biocLite("Biostrings")
biocLite("Biobase") # -> ExpressionSet
biocLite("IRanges")
biocLite("GenomicRanges") # -> SummarizedExperiment
biocLite("ShortRead")
biocLite("Rsamtools")
biocLite("GenomicAlignments")
biocLite("Rsubread")
biocLite("rtracklayer")
biocLite("genefilter")
biocLite("BSgenome")
biocLite("GenomicFeatures")
biocLite("VariantAnnotation")
biocLite("VariantFiltering")
biocLite("BiocParallel")
biocLite("GenomicFiles")
biocLite("biomaRt")
biocLite("AnnotationHub")
biocLite("ensemblVEP")

biocLite("Homo.sapiens")
biocLite("BSgenome.Hsapiens.UCSC.hg19")

biocLite("Mus.musculus")
biocLite("BSgenome.Mmusculus.UCSC.mm10")

# Meth-seq
biocLite("minfi")
biocLite(c("IlluminaHumanMethylation450kmanifest","IlluminaHumanMethylation450kanno.ilmn12.hg19"))
biocLite("bumphunter")

biocLite("WGCNA")
biocLite("Rsubread")
biocLite("DESeq2")
biocLite("DEXSeq")
biocLite("edgeR")
biocLite("cummeRbund")
biocLite("vsn")
biocLite("sva")
biocLite("airway")
biocLite("pasilla")
biocLite("pasillaBamSubset")
biocLite("affy")
biocLite("plier")
biocLite("oligo")
biocLite("limma")
biocLite("gcrma")
biocLite("BiocStyle")
biocLite("ReportingTools")
biocLite("biovizBase")
biocLite("Gviz")
biocLite("ggbio")
biocLite("epivizr")
biocLite("ComplexHeatmap")
biocLite("GEOquery")
biocLite("ArrayExpress")
biocLite("SRAdb")
biocLite("GO.db")
biocLite("KEGG.db")
biocLite("Category")
biocLite("GOstats")
biocLite("GOexpress")
biocLite("topGO")
biocLite("sigPathway")
biocLite("GSEABase")
biocLite("GSEAlm")
biocLite("PGSEA")
biocLite("GlobalAncova")
biocLite("categoryCompare")
biocLite("EnrichmentBrowser")
biocLite("npGSEA")
biocLite("RSNPset")
biocLite("cpvSNP")
biocLite("RRHO")


biocLite("snpStats")
```
